# Generated by Django 5.2.5 on 2025-10-02 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productattribute_price_productattribute_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='products.product')),
            ],
        ),
    ]
