# Generated by Django 5.2.5 on 2025-09-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], max_length=20)),
                ('min_weight_g', models.PositiveIntegerField(default=0)),
                ('max_weight_g', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priority', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['priority', 'min_weight_g'],
            },
        ),
    ]
