# Generated by Django 5.2.5 on 2025-09-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_deliveryrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Order Confirmed'), ('processing', 'Delivery Processing'), ('delivered', 'Order Delivered')], default='confirmed', max_length=20),
        ),
    ]
